#!/usr/bin/env python3
# Copyright (C) 2026 NAVRobotec Pvt Ltd
# Author: Ragnar Vallhala
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""gen_fft_tables.py — emit const-in-flash twiddle + window tables for the FC FFT.

The maths-interface FFT (firmware/src/maths/fft.c) can build its twiddle factors
at init via m_fft_make_twiddles() (sinf/cosf into a buffer), but the design
(reference-autopilots-comparison.md §10.6) prefers a CONST table in flash:
deterministic, zero init cost, zero heap, no boot-time trig. This script emits
that header.

A single full-N forward twiddle table of N/2 entries serves the whole module:
the complex core indexes it with a stride and the real-FFT wrapper reuses it
(W_{N/2}^k == W_N^{2k}). A Hann analysis window of N floats is emitted alongside
for the notch front-end.

Usage:
    python3 tools/gen_fft_tables.py 128 > firmware/include/maths/fft_tables_N128.h

Output is deterministic; regenerate and diff if you change N.
"""
import math
import sys


def fmt(x: float) -> str:
    """Round-trippable float literal, with an 'f' suffix for single precision."""
    # repr() gives the shortest string that round-trips to the same double; the
    # 'f' suffix truncates to float at compile time, matching the runtime path.
    return f"{x!r}f"


def emit(n: int) -> str:
    if n < 2 or (n & (n - 1)) != 0:
        raise SystemExit(f"N must be a power of two >= 2, got {n}")

    guard = f"VAYU_MATHS_FFT_TABLES_N{n}_H"
    half = n // 2
    out = []
    w = out.append

    w(f"/* fft_tables_N{n}.h — GENERATED by tools/gen_fft_tables.py {n}.  DO NOT EDIT.")
    w(" *")
    w(" * Const-in-flash forward twiddle factors and Hann window for the N=%d FFT" % n)
    w(" * (see include/maths/maths_interface.h).  Regenerate with:")
    w(f" *   python3 tools/gen_fft_tables.py {n} > firmware/include/maths/fft_tables_N{n}.h")
    w(" */")
    w(f"#ifndef {guard}")
    w(f"#define {guard}")
    w("")
    w('#include "maths/maths_interface.h"')
    w("")
    w(f"#define FFT_TABLE_N {n}")
    w("")
    w("/* W_N^k = exp(-i*2*pi*k/N), k = 0 .. N/2-1  (forward twiddles). */")
    w(f"static const fft_complex_t FFT_TWIDDLE_N{n}[{half}] = {{")
    for k in range(half):
        ang = -2.0 * math.pi * k / n
        w(f"  {{{fmt(math.cos(ang))}, {fmt(math.sin(ang))}}},")
    w("};")
    w("")
    w("/* Hann analysis window: w[i] = 0.5*(1 - cos(2*pi*i/(N-1))). */")
    w(f"static const float FFT_HANN_N{n}[{n}] = {{")
    line = "  "
    for i in range(n):
        val = 0.5 * (1.0 - math.cos(2.0 * math.pi * i / (n - 1)))
        tok = fmt(val) + ","
        if len(line) + len(tok) + 1 > 78:
            w(line.rstrip())
            line = "  "
        line += tok + " "
    if line.strip():
        w(line.rstrip())
    w("};")
    w("")
    w(f"#endif /* {guard} */")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 128
    sys.stdout.write(emit(n))
